- name: Install Zabbix Server
  hosts: zabbix-server-local
  user: root
  remote_user: vagrant
  sudo: yes

  roles:
    - common
    - zabbix-server

- name: Install Zabbix Agent
  hosts:
    - zabbix-server-local
    - zabbix-agents-local
  user: root
  remote_user: vagrant
  sudo: yes

  roles:
    - common
    - zabbix-agent
