---
- name: restart zabbix-server
  service: name=zabbix-server state=restarted

- name: create database
  shell: echo "create database zabbix character set utf8 collate utf8_bin; grant all privileges on zabbix.* to 'zabbix'@'localhost' identified by 'zabbix';" | mysql -uroot
#  notify: create schema

- name: create schema
  shell: mysql -uroot zabbix < /usr/share/doc/zabbix-server-mysql-{{ zabbix_version.stdout }}/create/schema.sql
#  when: zabbix_version.stdout != ""
#  notify: create images

- name: create images
  shell: mysql -uroot zabbix < /usr/share/doc/zabbix-server-mysql-{{ zabbix_version.stdout }}/create/images.sql
#  when: zabbix_version.stdout != ""
#  notify: create data

- name: create data
  shell: mysql -uroot zabbix < /usr/share/doc/zabbix-server-mysql-{{ zabbix_version.stdout }}/create/data.sql
#  when: zabbix_version.stdout != ""
