---
- name: Disable Iptables
  service: name=iptables state=stopped

- name: Zabbix Repository Installation for CentOS6
  yum: name=http://repo.zabbix.com/zabbix/2.4/rhel/6/x86_64/zabbix-release-2.4-1.el6.noarch.rpm state=present
  when: ansible_distribution == "CentOS" and ansible_distribution_major_version == "6"

- name: Zabbix Repository Installation for CentOS7
  yum: name=http://repo.zabbix.com/zabbix/2.4/rhel/7/x86_64/zabbix-release-2.4-1.el7.noarch.rpm state=present
  when: ansible_distribution == "CentOS" and ansible_distribution_major_version == "7"

- name: Zabbix Base Installation
  yum: name=zabbix state=present

- name: Get Zabbix Revision Information
  shell: rpm -q zabbix | sed -e 's/zabbix-//' | sed -e 's/-.*//'
  register: zabbix_version

- name: Database Installation for CentOS6
  yum: name={{ item }} state=present
  with_items:
    - mysql-server
  when: ansible_distribution == "CentOS" and ansible_distribution_major_version == "6"

- name: Database Installation for CentOS7
  yum: name={{ item }} state=present
  with_items:
    - mariadb-server
    - mariadb-embedded
    - mariadb-embedded-devel
    - mariadb-libs
  when: ansible_distribution == "CentOS" and ansible_distribution_major_version == "7"

- name: Zabbix Installation
  yum: name={{ item }} state=present
  with_items:
    - httpd
    - zabbix-server-mysql
    - zabbix-web-mysql
  notify:
    - create database
    - create schema
    - create images
    - create data

- name: MySQL Restart
  service: name=mysqld state=started
  when: ansible_distribution == "CentOS" and ansible_distribution_major_version == "6"

- name: MariaDB Restart
  service: name=mariadb state=started
  when: ansible_distribution == "CentOS" and ansible_distribution_major_version == "7"

- name: Copy Apache Configuration
  file: src=zabbix.conf dest=/etc/httpd/conf.d/zabbix.conf
  notify: restart httpd

- name: Copy Zabbix Configuration
  file: src=zabbix_server.conf dest=/etc/zabbix/zabbix_server.conf
  notify: restart zabbix-server

- include: enable_service.yml

