---
- name: Disable Iptables
  service: name=iptables state=stopped

- name: Update Zabbix Repository
  action: command /bin/rpm -Uvh http://repo.zabbix.com/zabbix/2.4/rhel/6/x86_64/zabbix-release-2.4-1.el6.noarch.rpm

- name: Clear Yum Repository
  shell: yum clean all

- name: Update Zabbix Packages
  yum: name={{ item }} state=latest
  with_items:
    - zabbix-agent
    - zabbix
  notify: restart zabbix-agent
