---
- name: Disable Iptables
  service: name=iptables state=stopped

- name: Zabbix Repository Installation
  action: command /bin/rpm -ivh http://repo.zabbix.com/zabbix/2.4/rhel/6/x86_64/zabbix-release-2.4-1.el6.noarch.rpm

- name: Zabbix Installation
  yum: name=zabbix-agent state=installed

- name: Copy Configuration Zabbix Agent
  template: src=zabbix_agentd.conf dest=/etc/zabbix/zabbix_agentd.conf
  notify: restart zabbix-agent
