---
- name: Disable Iptables
  service: name=iptables state=stopped

- name: Zabbix Repository Installation for CentOS6
#  action: command /bin/rpm -ivh http://repo.zabbix.com/zabbix/2.4/rhel/6/x86_64/zabbix-release-2.4-1.el6.noarch.rpm
  yum: name=http://repo.zabbix.com/zabbix/2.4/rhel/6/x86_64/zabbix-release-2.4-1.el6.noarch.rpm state=present
  when: ansible_distribution == "CentOS" and ansible_distribution_major_version == "6"

- name: Zabbix Repository Installation for CentOS7
  yum: name=http://repo.zabbix.com/zabbix/2.4/rhel/7/x86_64/zabbix-release-2.4-1.el7.noarch.rpm state=present
  when: ansible_distribution == "CentOS" and ansible_distribution_major_version == "7"

- name: Zabbix Installation
  yum: name=zabbix-agent state=present

- name: Copy Configuration Zabbix Agent
  template: src=zabbix_agentd.conf dest=/etc/zabbix/zabbix_agentd.conf
  notify: restart zabbix-agent
